# values.yaml (base defaults)
identity:
  issuer:
    crtExpiry: "87600h" # example longer lifetime (10 years) — tune as needed

proxy:
  resources:
    requests:
      cpu: "10m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

controller:
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# Ensure mTLS is enabled (Linkerd manages mTLS by default through identity)
policy:
  enabled: true
