# dev overrides
proxy:
  resources:
    requests:
      cpu: "10m"
      memory: "64Mi"
    limits:
      cpu: "150m"
      memory: "256Mi"

controller:
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "512Mi"

# lower resource footprints in dev
