# staging overrides
proxy:
  resources:
    requests:
      cpu: "25m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

controller:
  replicaCount: 2
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
