apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: linkerd
    app.kubernetes.io/component: service-mesh
    environment: development
    project: platform-tools
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-tools
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-control-plane
    targetRevision: 1.16.11
    helm:
      values: |
        # Development Environment Configuration
        linkerdNamespace: linkerd
        
        # Control plane replicas for development
        controllerReplicas: 1
        destinationReplicas: 1
        identityReplicas: 1
        
        # Development logging (debug level)
        controllerLogLevel: debug
        
        # Proxy configuration for development
        proxy:
          logLevel: debug
          logFormat: json
          resources:
            cpu:
              request: 50m
              limit: 500m
            memory:
              request: 10Mi
              limit: 128Mi
        
        # Identity and mTLS configuration
        identity:
          issuer:
            scheme: linkerd.io/tls
            clockSkewAllowance: 20s
            issuanceLifetime: 24h
        
        # Development environment labels
        podAnnotations:
          environment: development
          managed-by: argocd-dev
          debug: "enabled"
          
        # Resource limits for development
        resources:
          cpu:
            request: 100m
            limit: 1
          memory:
            request: 128Mi
            limit: 512Mi
            
        # Disable PDB for development (easier debugging)
        enablePodDisruptionBudget: false
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 2103
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
  - name: Description
    value: "Linkerd Service Mesh - Development Environment"
  - name: Environment
    value: "development"
  - name: Project
    value: "platform-tools"
  - name: Helm Chart
    value: "Official Linkerd Helm Chart"
  - name: mTLS
    value: "Enabled for zero-trust networking"