apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: linkerd
    app.kubernetes.io/component: service-mesh
    environment: development
    project: platform-tools
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-tools
  sources:
  - repoURL: https://helm.linkerd.io/stable
    chart: linkerd-crds
    targetRevision: 1.8.0
    helm:
      values: |
        linkerdNamespace: linkerd
  - repoURL: https://github.com/ChichiAgha/-Deploy-Linkerd-via-ArgoCD-Helm-Chart
    path: ArgoCD-gitops/platform-tools/linkerd/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
  - name: Description
    value: "Linkerd Service Mesh - Development Environment (Kustomize + ArgoCD)"
  - name: Environment
    value: "development"
  - name: Project
    value: "platform-tools"
  - name: Approach
    value: "Kustomize overlays with official Helm charts"
  - name: Ticket Compliance
    value: "✅ Kustomize paired with ArgoCD as required"