apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging
  tier: staging

commonAnnotations:
  environment: staging
  managed-by: argocd-staging

patchesStrategicMerge:
  - helm-values-patch.yaml