apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkerd

resources:
  - namespace.yaml

# Common labels for GitOps tracking
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: linkerd
    app.kubernetes.io/part-of: linkerd-service-mesh
    app.kubernetes.io/managed-by: argocd
    platform.project: platform-tools

# Common annotations
commonAnnotations:
  argocd.argoproj.io/managed: "true"
  config.linkerd.io/created-by: argocd-gitops