apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkerd

resources:
  - namespace.yaml
  - linkerd-config.yaml

# Linkerd CRDs via Helm
helmCharts:
  - name: linkerd-crds
    repo: https://helm.linkerd.io/stable
    version: 1.8.0
    namespace: linkerd
    releaseName: linkerd-crds

# Common labels for GitOps tracking
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: linkerd
    app.kubernetes.io/part-of: linkerd-service-mesh
    app.kubernetes.io/managed-by: argocd
    platform.project: platform-tools

# Common annotations
commonAnnotations:
  argocd.argoproj.io/managed: "true"
  config.linkerd.io/created-by: argocd-gitops