apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-prod
  namespace: argocd
spec:
  project: platform-tools
  source:
    repoURL: 'https://github.com/ChichiAgha/-Deploy-Linkerd-via-ArgoCD-Helm-Chart.git'
    targetRevision: HEAD
    path: Platform-Tools/argos-cd/overlays/linkered/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"
  info:
    - name: "purpose"
      value: "Linkerd service mesh (production)"
