apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-dev-values

# Development-specific Helm values override
helmCharts:
  - name: linkerd-control-plane
    repo: https://helm.linkerd.io/stable
    version: 1.16.11
    namespace: linkerd
    releaseName: linkerd-control-plane-dev
    valuesInline:
      # Development configuration
      controllerReplicas: 1
      destinationReplicas: 1
      identityReplicas: 1
      
      # Enhanced logging for development
      controllerLogLevel: debug
      
      # Development proxy configuration
      proxy:
        logLevel: debug,linkerd=debug
        logFormat: json
        resources:
          cpu:
            request: 50m
            limit: 500m
          memory:
            request: 10Mi
            limit: 128Mi
      
      # Development environment annotations
      podAnnotations:
        environment: development
        debug: "enabled"
        
      # Resource limits for development (generous for debugging)
      resources:
        cpu:
          request: 100m
          limit: 1
        memory:
          request: 128Mi
          limit: 512Mi
          
      # Disable resource constraints for easier development
      enablePodDisruptionBudget: false