apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Development-specific Helm chart override
helmCharts:
  - name: linkerd-control-plane
    repo: https://helm.linkerd.io/stable
    version: 1.16.11
    namespace: linkerd
    releaseName: linkerd-control-plane
    valuesInline:
      # Development configuration
      controllerReplicas: 1
      destinationReplicas: 1
      identityReplicas: 1
      
      # Enhanced logging for development
      controllerLogLevel: debug
      
      # Development proxy configuration
      proxy:
        logLevel: debug,linkerd=debug
        logFormat: json
        resources:
          cpu:
            request: 50m
            limit: 500m
          memory:
            request: 10Mi
            limit: 128Mi
      
      # Development environment annotations
      podAnnotations:
        environment: development
        debug: "enabled"
        
      # Resource limits for development
      resources:
        cpu:
          request: 100m
          limit: 1
        memory:
          request: 128Mi
          limit: 512Mi
          
      # Disable PDB for development (easier debugging)
      enablePodDisruptionBudget: false

# Development-specific labels
labels:
- includeSelectors: true
  pairs:
    environment: development
    tier: dev

# Development-specific annotations  
commonAnnotations:
  environment: development
  managed-by: argocd-dev