apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Development-specific labels
labels:
- includeSelectors: true
  pairs:
    environment: development
    tier: dev

# Development-specific annotations  
commonAnnotations:
  environment: development
  managed-by: argocd-dev