apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

labels:
- includeSelectors: true
  pairs:
    environment: development
    tier: dev

commonAnnotations:
  environment: development
  managed-by: argocd-dev